export const CLIP_TTL_SECONDS = 600;

export const PUBLIC_MAX_TEXT_LENGTH = 1000000;

export const PUBLIC_MAX_FILE_SIZE = 700 * 1024;

export const ADMIN_MAX_TEXT_LENGTH = 4500000;

export const ADMIN_MAX_FILE_SIZE = 4.5 * 1024 * 1024;

export const PUBLIC_ALLOWED_FILE_TYPES = [
  "text/plain",
  "text/csv",
  "text/tab-separated-values",
  "text/markdown",
  "text/html",
  "text/css",
  "text/javascript",
  "text/xml",
  "text/x-yaml",
  "text/calendar",
  "text/vcard",

  "text/x-python",
  "text/x-java-source",
  "text/x-c",
  "text/x-c++",
  "text/x-csharp",
  "text/x-go",
  "text/x-rust",
  "text/x-ruby",
  "text/x-php",
  "text/x-swift",
  "text/x-kotlin",
  "text/x-scala",
  "text/x-typescript",
  "text/x-lua",
  "text/x-perl",
  "text/x-shellscript",
  "text/x-sql",
  "text/x-toml",
  "text/x-diff",
  "text/x-r",
  "text/x-dart",
  "text/x-haskell",
  "text/x-elixir",
  "text/x-erlang",
  "text/x-clojure",
  "text/x-groovy",
  "text/x-objective-c",
  "text/x-fortran",
  "text/x-pascal",
  "text/x-matlab",
  "text/x-cmake",
  "text/x-dockerfile",
  "text/x-makefile",

  "application/json",
  "application/xml",
  "application/x-yaml",
  "application/toml",
  "application/sql",
  "application/graphql",
  "application/ld+json",
  "application/x-sh",
  "application/x-httpd-php",

  "application/pdf",
  "application/rtf",
  "application/msword",

  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",

  "application/vnd.oasis.opendocument.text",

  "application/vnd.ms-excel",

  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",

  "application/vnd.oasis.opendocument.spreadsheet",

  "application/vnd.ms-powerpoint",

  "application/vnd.openxmlformats-officedocument.presentationml.presentation",

  "application/vnd.oasis.opendocument.presentation",

  "application/octet-stream",
];

export const ADMIN_ALLOWED_FILE_TYPES = [
  ...PUBLIC_ALLOWED_FILE_TYPES,

  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
  "image/svg+xml",
  "image/bmp",
  "image/tiff",
  "image/x-icon",
  "image/vnd.microsoft.icon",
  "image/avif",
  "image/apng",
  "image/heic",
  "image/heif",

  "audio/mpeg",
  "audio/mp3",
  "audio/wav",
  "audio/ogg",
  "audio/flac",
  "audio/aac",
  "audio/mp4",
  "audio/webm",
  "audio/opus",

  "video/mp4",
  "video/webm",
  "video/ogg",
  "video/quicktime",
  "video/x-matroska",
  "video/mpeg",
  "video/3gpp",

  "application/zip",
  "application/x-zip-compressed",
  "application/x-rar-compressed",
  "application/vnd.rar",
  "application/gzip",
  "application/x-7z-compressed",
  "application/x-tar",
  "application/x-bzip2",

  "image/vnd.adobe.photoshop",
  "application/postscript",

  "font/ttf",
  "font/otf",
  "font/woff",
  "font/woff2",

  "application/epub+zip",
  "application/x-mobipocket-ebook",
];

export const PUBLIC_SAFE_EXTENSIONS = [
  ".txt",
  ".log",
  ".md",
  ".csv",
  ".tsv",
  ".html",
  ".htm",
  ".css",
  ".js",
  ".ts",
  ".jsx",
  ".tsx",
  ".py",
  ".java",
  ".c",
  ".h",
  ".cpp",
  ".hpp",
  ".cc",
  ".cs",
  ".go",
  ".rs",
  ".rb",
  ".php",
  ".swift",
  ".kt",
  ".scala",
  ".lua",
  ".pl",
  ".sh",
  ".bash",
  ".sql",
  ".json",
  ".xml",
  ".yaml",
  ".yml",
  ".toml",
  ".ini",
  ".cfg",
  ".conf",
  ".env",
  ".gitignore",
  ".r",
  ".dart",
  ".hs",
  ".ex",
  ".exs",
  ".erl",
  ".clj",
  ".groovy",
  ".m",
  ".f90",
  ".pas",
  ".pdf",
  ".rtf",
  ".doc",
  ".docx",
  ".odt",
  ".xls",
  ".xlsx",
  ".ods",
  ".ppt",
  ".pptx",
  ".odp",
  ".diff",
  ".patch",
  ".cmake",
  ".makefile",
  ".dockerfile",
  ".vue",
  ".svelte",
  ".astro",
];

export const RATE_LIMIT = {
  MAX_REQUESTS: 10,
  WINDOW_SECONDS: 60,
};

export const CLIP_ID_LENGTH = 10;
export const RETRIEVAL_CODE_LENGTH = 6;
